# start

In [48]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np 

In [49]:
(x_train, y_train), (x_test,y_test) = datasets.cifar10.load_data()

In [50]:
y_train = y_train.reshape(-1, )
y_train[:5]

array([6, 9, 9, 4, 1], dtype=uint8)

In [51]:
classes = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]

In [52]:
def plot_sample(x, y, index):
    plt.figure(figsize=(15, 2))
    plt.imshow(x[index])
    plt.xlabel(classes[y[index]])

In [53]:
plot_sample(x_train,y_train,1)

Error in callback <function _draw_all_if_interactive at 0x0000020234812980> (for post_execute), with arguments args (),kwargs {}:


ValueError: object __array__ method not producing an array

ValueError: Output array must be a NumPy array

<Figure size 1500x200 with 1 Axes>

- Why do we need normalize the data?

In [54]:
x_train = x_train / 255
x_test = x_test / 255

In [55]:
ann = models.Sequential([
        layers.Flatten(input_shape=(32,32,3)),
        layers.Dense(3000, activation='relu'),
        layers.Dense(1000, activation='relu'),
        layers.Dense(10, activation='softmax')    
    ])

ann.compile(optimizer='SGD',
              loss='sparse_categorical_crossentropy', ## if the y is an array like [0 0 0 0 0 0 0 0 0 1 0], then use `categorical_crossentropy'
              metrics=['accuracy']) 

ann.fit(x_train, y_train, epochs=5)

Epoch 1/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 33s 21ms/step - accuracy: 0.3066 - loss: 1.9250
Epoch 2/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 34s 22ms/step - accuracy: 0.4221 - loss: 1.6447
Epoch 3/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 34s 21ms/step - accuracy: 0.4502 - loss: 1.5539
Epoch 4/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 34s 22ms/step - accuracy: 0.4771 - loss: 1.4914
Epoch 5/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 32s 21ms/step - accuracy: 0.4952 - loss: 1.4322


In [56]:
from sklearn.metrics import confusion_matrix , classification_report
import numpy as np
y_pred = ann.predict(x_test)
y_pred_classes = [np.argmax(element) for element in y_pred]

print("Classification Report: \n", classification_report(y_test, y_pred_classes))

RecursionError: maximum recursion depth exceeded

In [57]:
cnn = models.Sequential([
    # cnn
    layers.Conv2D(32, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D(pool_size=(2, 2)),
    # dense
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')  # softmax can normalize your probability
])

In [58]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [59]:
cnn.fit(x_train, y_train, epochs=10)

Epoch 1/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.3887 - loss: 1.6921
Epoch 2/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.5805 - loss: 1.2043
Epoch 3/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.6197 - loss: 1.0941
Epoch 4/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.6497 - loss: 1.0064
Epoch 5/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.6731 - loss: 0.9415
Epoch 6/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.6879 - loss: 0.8929
Epoch 7/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.7096 - loss: 0.8405
Epoch 8/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.7215 - loss: 0.7940
Epoch 9/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.7352 - loss: 0.7622
Epoch 10/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7469 - loss: 0.7284


In [60]:
cnn.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6502 - loss: 1.0409


[1.0722020864486694, 0.6434000134468079]

In [61]:
y_pred = cnn.predict(x_test)
y_pred[:5]

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([[1.52235851e-04, 7.56826057e-06, 4.59534087e-04, 5.87309062e-01,
        1.05100311e-03, 2.61353642e-01, 1.37330890e-01, 1.96744615e-04,
        1.19224237e-02, 2.16936300e-04],
       [1.13856152e-03, 4.60044220e-02, 3.25271259e-07, 4.14470982e-08,
        2.03210799e-08, 3.44482859e-10, 4.37571923e-10, 1.00247211e-09,
        9.52818871e-01, 3.77467040e-05],
       [5.52528739e-01, 7.09555000e-02, 1.43691106e-02, 4.91352333e-03,
        6.05305284e-03, 1.15880212e-04, 1.18071795e-04, 1.77631318e-03,
        3.41935754e-01, 7.23409886e-03],
       [4.82665747e-01, 3.42622921e-02, 2.68169314e-01, 4.65183239e-03,
        6.12574704e-02, 6.68248831e-05, 4.38870257e-03, 4.83906653e-04,
        1.43093914e-01, 9.60051955e-04],
       [2.88124693e-06, 2.93418962e-05, 3.76362377e-03, 1.91464706e-03,
        5.83344698e-02, 2.70359335e-04, 9.35674489e-01, 1.04332844e-06,
        6.64197387e-06, 2.48789388e-06]], dtype=float32)

In [62]:

y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]

[3, 8, 0, 0, 6]

In [63]:
y_test[:5]

array([[3],
       [8],
       [8],
       [0],
       [6]], dtype=uint8)

In [64]:
plot_sample(x_test, y_test,3)

TypeError: only integer scalar arrays can be converted to a scalar index

Error in callback <function _draw_all_if_interactive at 0x0000020234812980> (for post_execute), with arguments args (),kwargs {}:


ValueError: object __array__ method not producing an array

ValueError: Output array must be a NumPy array

<Figure size 1500x200 with 1 Axes>

In [65]:
classes[y_classes[3]]

'airplane'

In [66]:

classes[y_classes[3]]

'airplane'